server:
  port: 8030
eureka:
  instance:
    prefer-ip-address: true
  clinet:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: orderdetails
  datasource:
    name: anime_shop
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anime_shop?useUnicode=true&charactreUncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: wsj666
  redis:
    host: 192.168.66.133
    port: 6379
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.sj.entity
